<?PHP
$nom = $_GET['nombre'];
$apepater = $_GET['apepaterno'];
$apemater = $_GET['apematerno'];
$age = $_GET['edad'];
$num = $_GET['numero'];
$world = $_GET['pais'];
$paga = $_GET['pago'];
$emegercicorre = $_GET['correoemerg'];
$emergencinum = $_GET['numeroemergencia'];
$corre = $_GET['correo'];

echo $nom."<br>";
echo $apepater."<br>";
echo $apemater."<br>";
echo $age."<br>";
echo $num."<br";
echo $world."<br>";
echo $paga."<br>";
echo $emegercicorre."<br>";
echo $emergencinum."<br>";
echo $corre.;